// Generated by gencpp from file plan_path/path_data.msg
// DO NOT EDIT!


#ifndef PLAN_PATH_MESSAGE_PATH_DATA_H
#define PLAN_PATH_MESSAGE_PATH_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lane_point.h>
#include <lane_point.h>
#include <lane_point.h>

namespace plan_path
{
template <class ContainerAllocator>
struct path_data_
{
  typedef path_data_<ContainerAllocator> Type;

  path_data_()
    : header()
    , path()
    , left()
    , right()  {
    }
  path_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , path(_alloc)
    , left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::plan_path::lane_point_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef  ::plan_path::lane_point_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::plan_path::lane_point_<ContainerAllocator>  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::plan_path::path_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_path::path_data_<ContainerAllocator> const> ConstPtr;

}; // struct path_data_

typedef ::plan_path::path_data_<std::allocator<void> > path_data;

typedef boost::shared_ptr< ::plan_path::path_data > path_dataPtr;
typedef boost::shared_ptr< ::plan_path::path_data const> path_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_path::path_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_path::path_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plan_path

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'plan_path': ['/home/try/CPPP/pathing/catkin_paththird/src/plan_path/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plan_path::path_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_path::path_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_path::path_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_path::path_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_path::path_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_path::path_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_path::path_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58efe92583de75a77636bc2578f6a67e";
  }

  static const char* value(const ::plan_path::path_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58efe92583de75a7ULL;
  static const uint64_t static_value2 = 0x7636bc2578f6a67eULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_path::path_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_path/path_data";
  }

  static const char* value(const ::plan_path::path_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_path::path_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
lane_point path\n\
lane_point left\n\
lane_point right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: plan_path/lane_point\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::plan_path::path_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_path::path_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.path);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_path::path_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_path::path_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "path: ";
    s << std::endl;
    Printer< ::plan_path::lane_point_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::plan_path::lane_point_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::plan_path::lane_point_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_PATH_MESSAGE_PATH_DATA_H
